index:
    path: /invoice/outgoing
    defaults: { _controller: 'App\Controller\InvoiceController::outgoing' }

login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::login' }

logout:
    path: /logout

register:
    path: /register
    defaults: { _controller: 'App\Controller\SecurityController::register' }

# Depends on sensio/framework-extra-bundle:^3.0 and doctrine/annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
